name: Deploy to Shuttle

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install latest Shuttle CLI via binstall
        run: |
          # 使用 binstall 进行更快速、可靠的二进制安装，确保是最新版本
          cargo install cargo-binstall
          cargo binstall -y cargo-shuttle

      - name: Update Cargo dependencies
        run: |
          cargo update

      - name: Create Shuttle.toml
        run: |
          echo 'name = "shuttle-app"' > Shuttle.toml

      - name: Create Project and Set Secrets
        env:
          SHUTTLE_API_KEY: ${{ secrets.SHUTTLE_API_KEY }}
          # Map secrets to environment variables for this step
          INPUT_UUID: ${{ secrets.UUID }}
          INPUT_NEZHA_SERVER: ${{ secrets.NEZHA_SERVER }}
          INPUT_NEZHA_PORT: ${{ secrets.NEZHA_PORT }}
          INPUT_NEZHA_KEY: ${{ secrets.NEZHA_KEY }}
          INPUT_ARGO_DOMAIN: ${{ secrets.ARGO_DOMAIN }}
          INPUT_ARGO_AUTH: ${{ secrets.ARGO_AUTH }}
          INPUT_ARGO_PORT: ${{ secrets.ARGO_PORT }}
          INPUT_CFIP: ${{ secrets.CFIP }}
          INPUT_CFPORT: ${{ secrets.CFPORT }}
          INPUT_NAME: ${{ secrets.NAME }}
          INPUT_FILE_PATH: ${{ secrets.FILE_PATH }}
          INPUT_SUB_PATH: ${{ secrets.SUB_PATH }}
        run: |
          cargo shuttle project create --name shuttle-app || true
          # Use shell syntax to provide default values if environment variables are not set
          cargo shuttle secrets set UUID="${INPUT_UUID:-86ecdec6-59a2-42bc-8d29-6887c0956b1e}"
          cargo shuttle secrets set NEZHA_SERVER="${INPUT_NEZHA_SERVER}"
          cargo shuttle secrets set NEZHA_PORT="${INPUT_NEZHA_PORT}"
          cargo shuttle secrets set NEZHA_KEY="${INPUT_NEZHA_KEY}"
          cargo shuttle secrets set ARGO_DOMAIN="${INPUT_ARGO_DOMAIN}"
          cargo shuttle secrets set ARGO_AUTH="${INPUT_ARGO_AUTH}"
          cargo shuttle secrets set ARGO_PORT="${INPUT_ARGO_PORT:-8080}"
          cargo shuttle secrets set CFIP="${INPUT_CFIP:-time.is}"
          cargo shuttle secrets set CFPORT="${INPUT_CFPORT:-443}"
          cargo shuttle secrets set NAME="${INPUT_NAME:-Shuttle}"
          cargo shuttle secrets set FILE_PATH="${INPUT_FILE_PATH:-./tmp}"
          cargo shuttle secrets set SUB_PATH="${INPUT_SUB_PATH:-sub}"

      - name: Deploy to Shuttle
        env:
          SHUTTLE_API_KEY: ${{ secrets.SHUTTLE_API_KEY }}
        run: |
          cargo shuttle deploy --name shuttle-app
