# 删除函数 async fn setup_environment()
# 在main函数中删除调用：setup_environment().await;
# 在github中设置变量 UUID、NEZHA_SERVER、NEZHA_KEY、ARGO_DOMAIN、ARGO_AUTH、CFIP、NAME
# 如果使用哪吒v0，还需要在github中设置 NEZHA_PORT

name: Deploy to Shuttle

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install latest Shuttle CLI and verify
        run: |
          cargo install cargo-binstall
          cargo binstall -y --force cargo-shuttle
          echo "Verifying Shuttle CLI version with absolute path..."
          # 使用绝对路径来调用，确保版本正确
          $HOME/.cargo/bin/cargo-shuttle --version

      - name: Create Project and Set Secrets
        env:
          SHUTTLE_API_KEY: ${{ secrets.SHUTTLE_API_KEY }}
          # 将 secrets 映射到环境变量
          INPUT_UUID: ${{ secrets.UUID }}
          INPUT_NEZHA_SERVER: ${{ secrets.NEZHA_SERVER }}
          INPUT_NEZHA_PORT: ${{ secrets.NEZHA_PORT }}
          INPUT_NEZHA_KEY: ${{ secrets.NEZHA_KEY }}
          INPUT_ARGO_DOMAIN: ${{ secrets.ARGO_DOMAIN }}
          INPUT_ARGO_AUTH: ${{ secrets.ARGO_AUTH }}
          INPUT_ARGO_PORT: ${{ secrets.ARGO_PORT }}
          INPUT_CFIP: ${{ secrets.CFIP }}
          INPUT_CFPORT: ${{ secrets.CFPORT }}
          INPUT_NAME: ${{ secrets.NAME }}
          INPUT_FILE_PATH: ${{ secrets.FILE_PATH }}
          INPUT_SUB_PATH: ${{ secrets.SUB_PATH }}
        run: |
          # 关键改动：使用绝对路径调用所有 shuttle 命令，并移除不正确的 'set' 关键字
          $HOME/.cargo/bin/cargo-shuttle project create --name shuttle-app || true
          $HOME/.cargo/bin/cargo-shuttle secrets UUID="${INPUT_UUID:-86ecdec6-59a2-42bc-8d29-6887c0956b1e}"
          $HOME/.cargo/bin/cargo-shuttle secrets NEZHA_SERVER="${INPUT_NEZHA_SERVER}"
          $HOME/.cargo/bin/cargo-shuttle secrets NEZHA_PORT="${INPUT_NEZHA_PORT}"
          $HOME/.cargo/bin/cargo-shuttle secrets NEZHA_KEY="${INPUT_NEZHA_KEY}"
          $HOME/.cargo/bin/cargo-shuttle secrets ARGO_DOMAIN="${INPUT_ARGO_DOMAIN}"
          $HOME/.cargo/bin/cargo-shuttle secrets ARGO_AUTH="${INPUT_ARGO_AUTH}"
          $HOME/.cargo/bin/cargo-shuttle secrets ARGO_PORT="${INPUT_ARGO_PORT:-8080}"
          $HOME/.cargo/bin/cargo-shuttle secrets CFIP="${INPUT_CFIP:-time.is}"
          $HOME/.cargo/bin/cargo-shuttle secrets CFPORT="${INPUT_CFPORT:-443}"
          $HOME/.cargo/bin/cargo-shuttle secrets NAME="${INPUT_NAME:-Shuttle}"
          $HOME/.cargo/bin/cargo-shuttle secrets FILE_PATH="${INPUT_FILE_PATH:-./tmp}"
          $HOME/.cargo/bin/cargo-shuttle secrets SUB_PATH="${INPUT_SUB_PATH:-sub}"

      - name: Deploy to Shuttle
        env:
          SHUTTLE_API_KEY: ${{ secrets.SHUTTLE_API_KEY }}
        run: |
          # 关键改动：使用绝对路径调用 deploy 命令
          $HOME/.cargo/bin/cargo-shuttle deploy --name shuttle-app
