name: Deploy to Shuttle

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install latest Shuttle CLI and verify
        run: |
          cargo install cargo-binstall
          cargo binstall -y --force cargo-shuttle
          echo "Verifying Shuttle CLI version..."
          cargo shuttle --version

      - name: Create Project and Set Secrets
        env:
          SHUTTLE_API_KEY: ${{ secrets.SHUTTLE_API_KEY }}
          # 将 secrets 映射到环境变量
          INPUT_UUID: ${{ secrets.UUID }}
          INPUT_NEZHA_SERVER: ${{ secrets.NEZHA_SERVER }}
          INPUT_NEZHA_PORT: ${{ secrets.NEZHA_PORT }}
          INPUT_NEZHA_KEY: ${{ secrets.NEZHA_KEY }}
          INPUT_ARGO_DOMAIN: ${{ secrets.ARGO_DOMAIN }}
          INPUT_ARGO_AUTH: ${{ secrets.ARGO_AUTH }}
          INPUT_ARGO_PORT: ${{ secrets.ARGO_PORT }}
          INPUT_CFIP: ${{ secrets.CFIP }}
          INPUT_CFPORT: ${{ secrets.CFPORT }}
          INPUT_NAME: ${{ secrets.NAME }}
          INPUT_FILE_PATH: ${{ secrets.FILE_PATH }}
          INPUT_SUB_PATH: ${{ secrets.SUB_PATH }}
        run: |
          cargo shuttle project create --name shuttle-app || true
          cargo shuttle secrets UUID="${INPUT_UUID:-86ecdec6-59a2-42bc-8d29-6887c0956b1e}"
          cargo shuttle secrets NEZHA_SERVER="${INPUT_NEZHA_SERVER}"
          cargo shuttle secrets NEZHA_PORT="${INPUT_NEZHA_PORT}"
          cargo shuttle secrets NEZHA_KEY="${INPUT_NEZHA_KEY}"
          cargo shuttle secrets ARGO_DOMAIN="${INPUT_ARGO_DOMAIN}"
          cargo shuttle secrets ARGO_AUTH="${INPUT_ARGO_AUTH}"
          cargo shuttle secrets ARGO_PORT="${INPUT_ARGO_PORT:-8080}"
          cargo shuttle secrets CFIP="${INPUT_CFIP:-time.is}"
          cargo shuttle secrets CFPORT="${INPUT_CFPORT:-443}"
          cargo shuttle secrets NAME="${INPUT_NAME:-Shuttle}"
          cargo shuttle secrets FILE_PATH="${INPUT_FILE_PATH:-./tmp}"
          cargo shuttle secrets SUB_PATH="${INPUT_SUB_PATH:-sub}"

      - name: Deploy to Shuttle
        env:
          SHUTTLE_API_KEY: ${{ secrets.SHUTTLE_API_KEY }}
        run: |
          cargo shuttle deploy --name shuttle-app
